// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_Books.Models;

#nullable disable

namespace MinimalAPI_Books.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20230908074656_Initial creation")]
    partial class Initialcreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI_Books.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearofPublication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R Tolkien",
                            Available = false,
                            Genre = "Fantasy",
                            Title = "Sagan om Ringen",
                            YearofPublication = "1954"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stephen King",
                            Available = true,
                            Genre = "Skräck",
                            Title = "Pestens tid",
                            YearofPublication = "1978"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jean M. Auel",
                            Available = true,
                            Genre = "Historisk fiktion",
                            Title = "Hästarnas dal",
                            YearofPublication = "1982"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Available = true,
                            Genre = "Romantik",
                            Title = "Stolthet och fördom",
                            YearofPublication = "1813"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Louisa May Alcott",
                            Available = false,
                            Genre = "Coming of age",
                            Title = "Unga kvinnor",
                            YearofPublication = "1868"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.K. Rowling",
                            Available = true,
                            Genre = "Fantasy",
                            Title = "Harry Potter och de vises sten",
                            YearofPublication = "1997"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Douglas Adams",
                            Available = true,
                            Genre = "Science ficion",
                            Title = "Liftarens guide till galaxen",
                            YearofPublication = "1979"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
